name: driver_app
description: Auto driver application for ride management
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # State Management
  provider: ^6.0.5
  # Network & API
  dio: ^5.3.2
  http: ^1.1.0
  socket_io_client: ^2.0.2
  # Location & Maps
  google_maps_flutter: ^2.4.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^10.0.0
  geocoding: ^2.1.0
  # Storage
  shared_preferences: ^2.2.0
  # UI Components
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  # Utils
  intl: ^0.18.1
  permission_handler: ^10.4.3
  image_picker: ^1.0.2
  url_launcher: ^6.1.12
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/ 